import type { Metadata } from "next";
import { Geist, Geist_Mono, Mina, Eczar } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mina = Mina({
  variable: "--font-mina",
  subsets: ["latin"],
  weight: "400",
});

const mingImperial = localFont({
  src: "./fonts/Ming_Imperial.ttf",
  variable: "--font-ming",
  weight: "400",
});

const eczar = Eczar({
  variable: "--font-eczar",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${mina.variable} ${mingImperial.variable} ${eczar.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
